export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAILED = 'FETCH_CONTACT_FAILED';

export const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';